# Default config for SVGO
#
# Usage:
#
# for d in Papirus/16x16/* Papirus/22x22/* Papirus/24x24/* \
#   Papirus/32x32/* Papirus/48x48/* Papirus/64x64/*
# do
#   svgo --config=.svgo.yml -f "$d"
# done
#
# - or -
#
# svgo --config=.svgo.yml -f Papirus/16x16/actions
#
# - or -
#
#   svgo --config=.svgo.yml -i FILE

full: true
multipass: true

plugins:

  # removes doctype declaration
  - removeDoctype

  # removes comments
  - removeComments

  # removes <metadata>
  - removeMetadata

  # removes editors namespaces, elements and attributes
  - removeEditorsNSData

  # cleanups attributes from newlines, trailing and repeating spaces
  - cleanupAttrs

  # removes unused IDs
  - cleanupIDs:
      minify: false

  # removes elements in <defs> without id
  - removeUselessDefs

  # rounds numeric values to the fixed precision
  # removes default ‘px’ units
  # opacity="0.72000004" => opactity=".72"
  # y="749.936002px" => y="749.936"
  - cleanupNumericValues:
      floatPrecision: 3
      leadingZero: true
      defaultPx: true
      convertToPx: false

  # rounds list of values to the fixed precision
  # viewBox="0 0 16px 16px" => viewBox="0 0 16 16"
  - cleanupListOfValues:
      floatPrecision: 2
      leadingZero: true
      defaultPx: true
      convertToPx: false

  # converts colors: rgb() to #rrggbb
  - convertColors:
      shorthex: false
      shortname: false

  # removes unknown elements content and attributes
  # don't touch attrs with default values
  - removeUnknownsAndDefaults:
      defaultAttrs: false

  # remove or cleanup enable-background attribute when possible
  - cleanupEnableBackground

  # removes empty <text> elements
  - removeEmptyText

  # collapses useless groups
  - collapseGroups

  # removes empty attributes
  - removeEmptyAttrs

  # removes empty container elements
  - removeEmptyContainers

  # removes unused namespaces declaration
  - removeUnusedNS

  # removes <desc> (only non-meaningful by default)
  - removeDesc

# configure the indent (default 4 spaces) used by `--pretty` here:
#
# @see https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L6 for more config options
#
js2svg:
  pretty: true
  indent: 1
